/* ==========================================================================
   VISUAL PARALLAX EDITOR LOGIC
   ========================================================================== */

(function initVisualEditor() {
  const body = document.body;
  const editorPanel = document.getElementById('parallax-editor');
  const closeBtn = document.getElementById('close-editor-btn');
  const targetDropdown = document.getElementById('editor-target-dropdown');
  const dragHandle = document.getElementById('editor-drag-handle');
  
  // Inputs
  const editY = document.getElementById('edit-y');
  const editYVal = document.getElementById('edit-y-val');
  const editX = document.getElementById('edit-x');
  const editXVal = document.getElementById('edit-x-val');
  const editOpStart = document.getElementById('edit-opacity-start');
  const editOpEnd = document.getElementById('edit-opacity-end');
  const editScrollStart = document.getElementById('edit-scroll-start');
  const editScrollEnd = document.getElementById('edit-scroll-end');
  const editScrub = document.getElementById('edit-scrub');
  const editScrubVal = document.getElementById('edit-scrub-val');
  
  const exportBtn = document.getElementById('editor-export-btn');

  let activeElement = null;
  let isDraggingPanel = false;
  let dragOffsetX = 0;
  let dragOffsetY = 0;
  
  // Store custom configurations generated by the user
  window.customParallaxConfig = {};

  // Populate Dropdown
  document.querySelectorAll('.p-layer').forEach(layer => {
    if (!layer.id) return; // Only layers with IDs
    const opt = document.createElement('option');
    opt.value = layer.id;
    opt.textContent = layer.id;
    targetDropdown.appendChild(opt);
  });

  // Handle Dropdown Change
  targetDropdown.addEventListener('change', (e) => {
    const val = e.target.value;
    if (val) {
      const el = document.getElementById(val);
      if (el) selectElement(el, true);
    } else {
      deselectCurrent();
    }
  });

  // --- PANEL DRAGGING LOGIC ---
  dragHandle.addEventListener('mousedown', (e) => {
    if (e.target === closeBtn) return;
    isDraggingPanel = true;
    const rect = editorPanel.getBoundingClientRect();
    dragOffsetX = e.clientX - rect.left;
    dragOffsetY = e.clientY - rect.top;
    dragHandle.style.cursor = 'grabbing';
  });
  document.addEventListener('mousemove', (e) => {
    if (!isDraggingPanel) return;
    const x = e.clientX - dragOffsetX;
    const y = e.clientY - dragOffsetY;
    editorPanel.style.left = `${x}px`;
    editorPanel.style.top = `${y}px`;
    editorPanel.style.right = 'auto'; // Disable right anchoring
    editorPanel.style.bottom = 'auto';
  });
  document.addEventListener('mouseup', () => {
    isDraggingPanel = false;
    dragHandle.style.cursor = 'grab';
  });

  // Toggle Edit Mode via Shift + E
  document.addEventListener('keydown', (e) => {
    if (e.shiftKey && e.key.toLowerCase() === 'e') {
      toggleEditor();
    }
  });

  closeBtn.addEventListener('click', () => toggleEditor(false));

  function toggleEditor(forceState) {
    const isEdit = forceState !== undefined ? forceState : !body.classList.contains('edit-mode');
    if (isEdit) {
      body.classList.add('edit-mode');
      editorPanel.classList.remove('hidden');
    } else {
      body.classList.remove('edit-mode');
      editorPanel.classList.add('hidden');
      deselectCurrent();
    }
  }

  // Handle Image Clicking for Selection
  document.addEventListener('click', (e) => {
    if (!body.classList.contains('edit-mode')) return;
    if (e.target.closest('.editor-panel')) return; // Ignore clicks in panel
    
    if (e.target.classList.contains('p-layer')) {
      e.preventDefault();
      e.stopPropagation();
      selectElement(e.target);
    } else {
      deselectCurrent();
    }
  });

  function deselectCurrent() {
    if (activeElement) activeElement.classList.remove('editor-selected');
    activeElement = null;
    targetDropdown.value = "";
  }

  function selectElement(el, skipDropdownUpdate = false) {
    deselectCurrent();
    activeElement = el;
    activeElement.classList.add('editor-selected');
    
    const elId = el.id || 'unnamed-layer';
    if (!skipDropdownUpdate) {
      targetDropdown.value = elId;
    }

    const config = window.customParallaxConfig[elId] || {
      y: 0, x: 0, scrub: 0,
      opacityStart: 1, opacityEnd: 1,
      scrollStart: 0, scrollEnd: 1000
    };

    updateUIFromConfig(config);
  }

  // Sync range and number inputs and trigger Live Apply
  function syncInputs(range, number) {
    range.addEventListener('input', () => { number.value = range.value; applyChanges(); });
    number.addEventListener('input', () => { range.value = number.value; applyChanges(); });
  }
  syncInputs(editY, editYVal);
  syncInputs(editX, editXVal);
  syncInputs(editScrub, editScrubVal);

  // Trigger apply on non-range number inputs too
  [editOpStart, editOpEnd, editScrollStart, editScrollEnd].forEach(input => {
    input.addEventListener('input', applyChanges);
  });

  function updateUIFromConfig(config) {
    editY.value = config.y; editYVal.value = config.y;
    editX.value = config.x; editXVal.value = config.x;
    editScrub.value = config.scrub || 0; editScrubVal.value = config.scrub || 0;
    editOpStart.value = config.opacityStart;
    editOpEnd.value = config.opacityEnd;
    editScrollStart.value = config.scrollStart;
    editScrollEnd.value = config.scrollEnd;
  }

  // Apply / Live Preview (Now called automatically on any input change!)
  function applyChanges() {
    if (!activeElement) return;
    
    const elId = activeElement.id;
    if (!elId) return;

    const scrubVal = parseFloat(editScrubVal.value);
    
    const config = {
      y: parseFloat(editYVal.value),
      x: parseFloat(editXVal.value),
      scrub: scrubVal === 0 ? true : scrubVal, // If 0, strict scroll. If > 0, smoothed scrub time.
      opacityStart: parseFloat(editOpStart.value),
      opacityEnd: parseFloat(editOpEnd.value),
      scrollStart: parseInt(editScrollStart.value, 10),
      scrollEnd: parseInt(editScrollEnd.value, 10)
    };

    window.customParallaxConfig[elId] = config;

    // 1. Kill any existing GSAP tweens (including those inside timelines from app.js)
    gsap.killTweensOf(activeElement);

    // 2. Aggressively kill any ScrollTriggers that might be controlling this element
    ScrollTrigger.getAll().forEach(st => {
      if (st.animation) {
        let targets = [];
        try { targets = st.animation.targets(); } catch(e) {}
        if (targets.includes(activeElement) || targets.includes('#' + elId) || targets[0] === activeElement) {
          st.kill();
        }
      }
      // If it was a custom ST created by this editor previously, kill it
      if (st.vars.id === `custom-st-${elId}`) {
        st.kill();
      }
    });

    const currentScale = getComputedStyle(document.documentElement).getPropertyValue('--scale') || 1;
    const s = (px) => `${px * currentScale}px top`;

    // CRITICAL FIX: Only clear transform and opacity. 
    // DO NOT clear "all" because it strips the inline left/top/width/height CSS from index.html!
    gsap.set(activeElement, { clearProps: "transform,opacity" });

    // Create the brand new ScrollTrigger with the user's live settings
    gsap.fromTo(activeElement,
      { x: 0, y: 0, opacity: config.opacityStart },
      {
        x: config.x,
        y: config.y,
        opacity: config.opacityEnd,
        ease: 'none',
        scrollTrigger: {
          trigger: '.scroll-wrapper',
          start: s(config.scrollStart),
          end: s(config.scrollEnd),
          scrub: config.scrub,
          id: `custom-st-${elId}`
        }
      }
    );

    // 3. FORCE GSAP to instantly recalculate and apply the current scroll position!
    // This ensures the image jumps to its new position instantly without the user needing to scroll.
    ScrollTrigger.refresh();
  }

  // Export Config
  exportBtn.addEventListener('click', () => {
    const jsonStr = JSON.stringify(window.customParallaxConfig, null, 2);
    navigator.clipboard.writeText(jsonStr).then(() => {
      alert('Config copied to clipboard!\n\nPaste this in the chat so I can save it:\n\n' + jsonStr);
    }).catch(() => {
      alert('Here is your config (Copy this and send to chat):\n\n' + jsonStr);
    });
  });

})();
